[radio]
address = 0x4000_1000
size = 0x1000

# spi and twi 0 are on the same peripheral and mutually exclusive
[spitwi0]
address = 0x4000_3000
size = 0x1000

# spi and twi 1 are on the same peripheral and mutually exclusive
[spitwi1]
address = 0x4000_4000
size = 0x1000

[gpiote]
address = 0x4000_6000
size = 0x1000

[wdt]
address = 0x4001_0000
size = 0x1000

[nvmc]
address = 0x4001_E000
size = 0x1000

# spi2 is on its own and can't also be used as a twi
[spi2]
address = 0x4002_3000
size = 0x1000

[gpio]
address = 0x5000_0000
size = 0x1000
